import { certificateDataType } from "@/types/certificateData.type";


export const certificatesData: certificateDataType[] = [
  {
    title: "CS50 Databases with SQL",
    description: "This is a SQL course, which in I learn about Querying, Pattern Matching, Aggregate Functions. Relating data with primary and foreign keys, Relationships, ERD, Subqueries, Joints, Sets, and to group data. How to design databases with schema files, Normalizing, Data Types, Table Constraints, Column Constraints, and Altering Tables. How to insert data, insert from CSV files, delete data, Triggers, Soft Deletions. Common Table Expressions, Views for Partitioning, Views for Securing. How to optimize a database with Indexes, Covering Indexes, VACUUM, Transactions, ACID, COMMIT, ROLLBACK, Race Conditions, Locks. Make DDBB Scalable with MySQL, Stored Procedures and PostgreSQL, Vertical Scaling, Horizontal Scaling, Replication, Read Replicas, Sharding, Access Controls: GRANT, REVOKE. SQL Injection Attacks, Prepared Statements.",
    imageUrl: "https://i.postimg.cc/8zWqVX8v/CS50-SQL.png",
    imageAlt: "CS50 Harvard Databases with SQL Course Certificate",
    documentUrl: "https://certificates.cs50.io/592e207d-fc25-4497-9073-4aa12aeca9c6.pdf?size=letter",
    techs: ["SQL", "PostgreSQL", "SQLite", "MySQL"],
  },
  {
    title: "CS50 Artificial Intelligence",
    description: "Great course, I get the bases of Artificial Intelligence with this course. This course explores search algorithms (like DFS, BFS, A* search, Minimax), working with knowledge (Propositional Logic, Inference, Model Checking, First Order Logic), cases of uncertainty (Probability, Random Variables, Bayes' Rule, Bayesian Networks, Márkov Models), Machine Learning with Scikit-Learn (Supervised/Unsupervised/Reinforced Learning algorithms, Overfitting, Regularization, Clustering), Deep Learning watt TensorFlow (Neural Networks, Activation Functions. Gradient Descent. Backpropagation, CNN, RNN), and as ultimate Language (Naive Bayes, Word Representation, Attention, Transformers). A really complete AI course.",
    imageUrl: "https://i.postimg.cc/L4C3Vvqd/CS50-AI-min.png",
    imageAlt: "CS50 Harvard Artificial Intelligence Course Certificate",
    documentUrl: "https://certificates.cs50.io/e7bf8cba-c7d7-4a4f-bc87-a87c23cda397.pdf?size=letter",
    techs: ["Python", "TensorFlow", "Keras", "Scikit-Learn", "word2vec", "NLTK"],
  },
  {
    title: "Foundations of Retrieval Augmented Generation (RAG) Systems",
    description: "Learn the essentials of Retrieval-Augmented Generation (RAG) to enhance text generation accuracy. This path covers RAG basics, vector databases, semantic retrieval with embeddings, and building a complete RAG pipeline.",
    imageUrl: "https://i.postimg.cc/WbjwQDrk/Foundations_of_Retrieval_Augmented_Generation_(RAG)_Systems_min.png",
    imageAlt: "Foundations of Retrieval Augmented Generation (RAG) Systems CodeSignal Certificate",
    documentUrl: "https://codesignal.com/learn/certificates/cmcg99l7v0010l504z63c0ked/course-paths/237",
    techs: ["Python"],
  },
  {
    title: "CS50 Programming with Python",
    description: "I thoght that I won't learn something with this one, but I was very wrong. New things I learned was to manage Exceptions, Important libraries like sys or requests. Basic Unit Test with Pytest. Creating, editing and deleting files, read CSV files, I learn Regular Explessions and Object Oriented Programming between other functionalities and concepts.",
    imageUrl: "https://i.postimg.cc/kGpNXXrM/CS50-P-min.png",
    imageAlt: "CS50 Harvard Programming with Python Course Certificate",
    documentUrl: "https://certificates.cs50.io/393d42d4-3530-41ae-8af1-4c5e5377cdf1.pdf?size=letter",
    techs: ["Python"],
  },
  {
    title: "Scaling up RAG with Vector Databases",
    description: "Discover how to scale RAG systems using vector databases. Learn to preprocess documents, store embeddings in ChromaDB, retrieve relevant chunks, and construct prompts. Manage updates and large-scale ingestion with batch strategies for efficient retrieval.",
    imageUrl: "https://i.postimg.cc/gkdHfwRL/Scaling_up_RAG_with_Vector_Databases_min.png",
    imageAlt: "Scaling up RAG with Vector Databases CodeSignal Certificate",
    documentUrl: "https://codesignal.com/learn/certificates/cmcg99l7v0010l504z63c0ked/courses/1067",
    techs: ["ChromaDB", "Python"],
  },
  {
    title: "Text Representation Techniques for RAG Systems",
    description: "Learn essential text representation methods for RAG systems, from Bag-of-Words to embeddings. Explore how these techniques enhance understanding and retrieval, visualize embeddings with t-SNE, and compare BOW and embeddings in document retrieval and semantic search.",
    imageUrl: "https://i.postimg.cc/xTY3WkHM/Text_Representation_Techniques_for_RAG_Systems_min.png",
    imageAlt: "Text Representation Techniques for RAG Systems CodeSignal Certificate",
    documentUrl: "https://codesignal.com/learn/certificates/cmcg99l7v0010l504z63c0ked/courses/1066",
    techs: ["Python"],
  },
  {
    title: "CSS Master Udemy Certificate",
    description: "",
    imageUrl: "https://i.postimg.cc/HxBfDjzJ/UC-412cea72-9b35-427b-8019-cda1f36dc946-min.jpg",
    imageAlt: "CSS Master Course Certificate",
    documentUrl: "https://www.udemy.com/certificate/UC-412cea72-9b35-427b-8019-cda1f36dc946/",
    techs: ["CSS", "SASS", "Bootstrap"],
  },
  {
    title: "CS50 Computer Science Harvard Certificate",
    description: "This is a Computer Science and it was one of my first certificates. Here I used C (not now), to learn data structures (like lists, queues, stacks, trees, etc) and algorithms (like sort algorithms and search algorithms). Then David Malan (the teacher) explain the memory with a lot of details and that has open my mind to understand other things in programming (like VACUUM in SQL). And then we learn other technologies like C, Python, SQL, HTML, CSS, JavaScript, Flask. I'm sure that this course trained me for the next steps.",
    imageUrl: "https://i.postimg.cc/50bVWhMr/CS50x-min.png",
    imageAlt: "CS50 Harvard Computer Science Course Certificate",
    documentUrl: "https://certificates.cs50.io/7bb466dd-c10b-4769-bf63-4c885013b122.pdf?size=letter",
    techs: ["C", "HTML", "CSS", "JavaScript", "Python", "Flask", "SQL", "SQLite"],
  },
  {
    title: "Beyond Basic RAG: Improving our Pipeline",
    description: "Enhance your RAG pipeline with advanced retrieval techniques. Implement hybrid retrieval, iterative query refinement, and context summarization. Constrain LLM outputs to retrieved context, ensuring accuracy and minimizing hallucinations in final responses.",
    imageUrl: "https://i.postimg.cc/wTHQStJt/Beyond_Basic_RAG_Improving_our_Pipeline_min.png",
    imageAlt: "Beyond Basic RAG: Improving our Pipeline CodeSignal Certificate",
    documentUrl: "https://codesignal.com/learn/certificates/cmcg99l7v0010l504z63c0ked/courses/1068",
    techs: ["Python"],
  },
  {
    title: "Introduction to RAG",
    description: "Learn what Retrieval-Augmented Generation (RAG) is, why combining retrieval with generation can reduce hallucinations, and how a basic RAG workflow contrasts with naive prompting. This course is mostly informational, setting the stage for more hands-on work in later courses.",
    imageUrl: "https://i.postimg.cc/MKxmhcRB/Introduction_to_RAG_min.png",
    imageAlt: "Introduction to RAG CodeSignal Certificate",
    documentUrl: "https://codesignal.com/learn/certificates/cmcg99l7v0010l504z63c0ked/courses/1065",
    techs: ["Python"],
  },
  {
    title: "Scikit-Learn for Beginners Simplilearn Certificate",
    description: "",
    imageUrl: "https://i.postimg.cc/dtgzpPf2/9019235-93951051758414970139.png",
    imageAlt: "Scikit-Learn for Beginners Simplilearn Course Certificate",
    documentUrl: "https://certificates.simplicdn.net/share/9019235_93951051758414971759.pdf",
    techs: ["Scikit-Learn", "Python"],
  },
  {
    title: "JavaScript Master Udemy Certificate",
    description: "",
    imageUrl: "https://i.postimg.cc/9fP6bLqY/UC-35d8e60e-b268-4c04-9f90-f9fb3e614390-min.jpg",
    imageAlt: "JavaScript Master Course Certificate",
    documentUrl: "https://www.udemy.com/certificate/UC-35d8e60e-b268-4c04-9f90-f9fb3e614390/",
    techs: ["JavaScript", "JQuery", "Angular", "NodeJS"],
  },
]
// {
//   title: "",
//   description: "",
//   imageUrl: "",
//   imageAlt: "",
//   documentUrl: "",
//   techs: [],
// },